name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Install required system libraries
          sudo apt-get install -y curl libgit2-dev libfribidi-dev

      - name: Set up R 4.4.0
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
          Rscript -e 'devtools::install_github("mrc-ide/mlscluster")'

      - uses: r-lib/actions/setup-renv@v2

      - name: Run R script
        run: Rscript R/running.R

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
