name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Install required system libraries
          sudo apt-get install -y \
            build-essential \
            cmake \
            curl \
            libblas-dev \
            libbz2-dev \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libgit2-dev \
            libharfbuzz-dev \
            libicu-dev \
            liblapack-dev \
            liblzma-dev \
            libfribidi-dev \
            libjpeg-dev \
            libpng-dev \
            libssl-dev \
            libtiff5-dev \
            libxml2-dev \
            zlib1g-dev

      - name: Set up R 4.4.0
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e 'install.packages(c("devtools", "gitcreds"), repos = "https://cloud.r-project.org")'
          Rscript -e 'gitcreds::gitcreds_set(token = Sys.getenv("GITHUB_PAT"))'

          Rscript -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
          Rscript -e 'devtools::install_github("YuLab-SMU/ggtree@c17773c973d6c4036ee3af40a3957fb74d8ee9ff")'
          Rscript -e 'devtools::install_github("mrc-ide/mlscluster@e9f7939ab69a61bc310a968252d96177c59921ba")'

      - uses: r-lib/actions/setup-renv@v2

      - name: Run R script
        run: Rscript R/running.R

      - name: Consolidate output to results/
        run: |
          mv Rplots.pdf results/ || echo "Rplots.pdf not found"
          mv stat_results results/ || echo "stat_results not found"

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
